---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx
spec:
  selector:
    matchLabels:
      app: xxx
  template:
    metadata:
      labels:
        app: xxx
    spec:
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/xxx
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
---
apiVersion: v1
kind: Service
metadata:
  name: xxx
spec:
  type: ClusterIP
  selector:
    app: xxx
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx
spec:
  selector:
    matchLabels:
      app: xxx
  template:
    metadata:
      labels:
        app: xxx
    spec:
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/xxx
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
---
apiVersion: v1
kind: Service
metadata:
  name: xxx
spec:
  type: ClusterIP
  selector:
    app: xxx
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx
spec:
  selector:
    matchLabels:
      app: xxx
  template:
    metadata:
      labels:
        app: xxx
    spec:
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/xxx
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
---
apiVersion: v1
kind: Service
metadata:
  name: xxx
spec:
  type: ClusterIP
  selector:
    app: xxx
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx
spec:
  selector:
    matchLabels:
      app: xxx
  template:
    metadata:
      labels:
        app: xxx
    spec:
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/xxx
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
---
apiVersion: v1
kind: Service
metadata:
  name: xxx
spec:
  type: ClusterIP
  selector:
    app: xxx
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx
spec:
  selector:
    matchLabels:
      app: xxx
  template:
    metadata:
      labels:
        app: xxx
    spec:
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/xxx
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
---
apiVersion: v1
kind: Service
metadata:
  name: xxx
spec:
  type: ClusterIP
  selector:
    app: xxx
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx
spec:
  selector:
    matchLabels:
      app: xxx
  template:
    metadata:
      labels:
        app: xxx
    spec:
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/xxx
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
---
apiVersion: v1
kind: Service
metadata:
  name: xxx
spec:
  type: ClusterIP
  selector:
    app: xxx
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx
spec:
  selector:
    matchLabels:
      app: xxx
  template:
    metadata:
      labels:
        app: xxx
    spec:
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/xxx
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
---
apiVersion: v1
kind: Service
metadata:
  name: xxx
spec:
  type: ClusterIP
  selector:
    app: xxx
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx
spec:
  selector:
    matchLabels:
      app: xxx
  template:
    metadata:
      labels:
        app: xxx
    spec:
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/xxx
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
---
apiVersion: v1
kind: Service
metadata:
  name: xxx
spec:
  type: ClusterIP
  selector:
    app: xxx
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx
spec:
  selector:
    matchLabels:
      app: xxx
  template:
    metadata:
      labels:
        app: xxx
    spec:
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/xxx
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
---
apiVersion: v1
kind: Service
metadata:
  name: xxx
spec:
  type: ClusterIP
  selector:
    app: xxx
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx
spec:
  selector:
    matchLabels:
      app: xxx
  template:
    metadata:
      labels:
        app: xxx
    spec:
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/xxx
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
---
apiVersion: v1
kind: Service
metadata:
  name: xxx
spec:
  type: ClusterIP
  selector:
    app: xxx
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx
spec:
  selector:
    matchLabels:
      app: xxx
  template:
    metadata:
      labels:
        app: xxx
    spec:
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/xxx
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
---
apiVersion: v1
kind: Service
metadata:
  name: xxx
spec:
  type: ClusterIP
  selector:
    app: xxx
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080

---

